### ISSUE TITLE
Broken with NPM Version 3.x

### ISSUE THREAD

**Issue by TylorS** [Frikki/cli-release#1]
Although I have only tested this on NPM version 3.5.0, I suspect that this is failing due to the way NPM 3.x structures the `node_modules` folder. Changing the way that the files are found should solve this issue.

Running with npm 3.5.0 throws the following error

```
module.js:340
    throw err;
    ^

Error: Cannot find module '/home/tylor/code/moto/storage/node_modules/cli-release/node_modules/.bin/changelog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3
child_process.js:507
    throw err;
    ^


Error: Command failed: node /home/tylor/code/moto/storage/node_modules/cli-release/lib/../node_modules/.bin/changelog v0.1.1 CHANGELOG.tmp
module.js:340
    throw err;
    ^

Error: Cannot find module '/home/tylor/code/moto/storage/node_modules/cli-release/node_modules/.bin/changelog'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:289:25)
    at Function.Module.runMain (module.js:457:10)
    at startup (node.js:138:18)
    at node.js:974:3

    at checkExecSyncError (child_process.js:464:13)
    at execSync (child_process.js:504:13)
    at changelog (/home/tylor/code/moto/storage/node_modules/cli-release/lib/release.js:33:3)
    at release (/home/tylor/code/moto/storage/node_modules/cli-release/lib/release.js:51:3)
    at Object.<anonymous> (/home/tylor/code/moto/storage/node_modules/cli-release/lib/release.js:55:1)
    at Module._compile (module.js:425:26)
    at Object.Module._extensions..js (module.js:432:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
```

**Comment by Frikki** [comment]
I’ll fix it ASAP. Or make a PR.

Changing https://github.com/Frikki/cli-release/blob/master/lib/release.js#L33 to

``` js
execSync('node ' + process.cwd() + '/node_modules/.bin/changelog ' + releaseVersion + ' CHANGELOG.tmp');
```

... should probably do the trick.
